// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClp1W3QFGHe7-II-Utl_V_sdPyTgpTSUA',
    appId: '1:252254702095:web:240aa7b30984a6a3bdf17a',
    messagingSenderId: '252254702095',
    projectId: 'atharvaagi',
    authDomain: 'atharvaagi.firebaseapp.com',
    storageBucket: 'atharvaagi.appspot.com',
    measurementId: 'G-2X91FW162P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4ECTaNpsx6hJhOWe_W1G3YfYahzicJvU',
    appId: '1:252254702095:android:8225f75f7d63227bbdf17a',
    messagingSenderId: '252254702095',
    projectId: 'atharvaagi',
    storageBucket: 'atharvaagi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdt9FiceEiHYyri4G0FBwqaUS4Pe-i3pY',
    appId: '1:252254702095:ios:8677faf53c7dccc6bdf17a',
    messagingSenderId: '252254702095',
    projectId: 'atharvaagi',
    storageBucket: 'atharvaagi.appspot.com',
    iosClientId: '252254702095-dfuip5q9pjn5slvbetsj92pj186ju30r.apps.googleusercontent.com',
    iosBundleId: 'com.atharva.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdt9FiceEiHYyri4G0FBwqaUS4Pe-i3pY',
    appId: '1:252254702095:ios:ff162984931ee1b7bdf17a',
    messagingSenderId: '252254702095',
    projectId: 'atharvaagi',
    storageBucket: 'atharvaagi.appspot.com',
    iosClientId: '252254702095-rn4q0qim050c2b82l25a7hjl0jmdu79i.apps.googleusercontent.com',
    iosBundleId: 'com.example.agiApp',
  );
}
